<?php namespace Seek\Enums;

use MabeEnum\Enum;

/**
 * Location enum
 */
class Location extends Enum
{
    const ACT = 'locACT';
    const ADELAIDE = 'Adelaide';
    const ADELAIDE_HILLS_BAROSSA = 'AdelaideHillsBarossa';
    const ALBANY_GREAT_SOUTHERN = 'AlbanyGreatSouthern';
    const ALBURY_WODONGA_MURRAY = 'AlburyWodongaMurray';
    const ALICE_SPRINGS_CENTRAL_AUSTRALIA = 'AliceSpringsCentralAustralia';
    const AMERICAS = 'Americas';
    const ASIA_PACIFIC = 'AsiaPacific';
    const AUCKLAND = 'Auckland';
    const BAIRNSDALE_GIPPSLAND = 'BairnsdaleGippsland';
    const BALLARAT_CENTRAL_HIGHLANDS = 'BallaratCentralHighlands';
    const BAY_OF_PLENTY = 'BayofPlenty';
    const BENDIGO_GOLDFIELDS_MACEDON_RANGES = 'BendigoGoldfieldsMacedonRanges';
    const BLUE_MOUNTAINS_CENTRAL_WEST = 'BlueMountainsCentralWest';
    const BRISBANE = 'Brisbane';
    const BROOME_KIMBERLEY = 'BroomeKimberley';
    const BUNBURY_SOUTH_WEST = 'BunburySouthWest';
    const BUNDABERG_WIDE_BAY_BURNETT = 'BundabergWideBayBurnett';
    const CAIRNS_FAR_NORTH = 'CairnsFarNorth';
    const CANTERBURY = 'Canterbury';
    const CENTRAL_SOUTH_EAST = 'CentralSouthEast';
    const COFFS_HARBOUR_NORTH_COAST = 'CoffsHarbourNorthCoast';
    const COOBER_PEDY_OUTBACK_SA = 'CooberPedyOutbackSA';
    const DARWIN = 'Darwin';
    const DEVONPORT_NORTH_WEST = 'DevonportNorthWest';
    const DUBBO_CENTRAL_NSW = 'DubboCentralNSW';
    const EUROPE_RUSSIA = 'EuropeRussia';
    const FAR_WEST_NORTH_CENTRAL_NSW = 'FarWestNorthCentralNSW';
    const FLEURIEU_PENINSULA_KANGAROO_ISLAND = 'FleurieuPeninsulaKangarooIsland';
    const GEELONG_GREAT_OCEAN_ROAD = 'GeelongGreatOceanRoad';
    const GERALDTON_GASCOYNE_MIDWEST = 'GeraldtonGascoyneMidwest';
    const GISBORNE = 'GisborneRegion';
    const GLADSTONE_CENTRAL_QLD = 'GladstoneCentralQLD';
    const GOLD_COAST = 'GoldCoast';
    const GOSFORD_CENTRAL_COAST = 'GosfordCentralCoast';
    const GOULBURN_SOUTHERN_TABLELANDS = 'GoulburnSouthernTablelands';
    const HAWKES_BAY = 'HawkesBay';
    const HERVEY_BAY_FRASER_COAST = 'HerveyBayFraserCoast';
    const HOBART = 'Hobart';
    const HORSHAM_GRAMPIANS = 'HorshamGrampians';
    const IRELAND = 'Ireland';
    const KALGOORLIE_GOLDFIELDS_ESPERANCE = 'KalgoorlieGoldfieldsEsperance';
    const KATHERINE_NORTHERN_AUSTRALIA = 'KatherineNorthernAustralia';
    const LAUNCESTON_NORTH_EAST = 'LauncestonNorthEast';
    const LISMORE_FAR_NORTH_COAST = 'LismoreFarNorthCoast';
    const LONDON = 'London';
    const MACKAY_COALFIELDS = 'MackayCoalfields';
    const MANAWATU = 'Manawatu';
    const MANDURAH_PEEL = 'MandurahPeel';
    const MARLBOROUGH = 'Marlborough';
    const MELBOURNE = 'Melbourne';
    const MIDDLE_EAST_AFRICA = 'MiddleEastAfrica';
    const MILDURA_MURRAY = 'MilduraMurray';
    const MORNINGTON_PENINSULA_BASS_COAST = 'MorningtonPeninsulaBassCoast';
    const MT_GAMBIER_LIMESTONE_COAST = 'MtGambierLimestoneCoast';
    const MT_ISA_WESTERN_QLD = 'MtIsaWesternQLD';
    const NEWCASTLE_MAITLAND_HUNTER = 'NewcastleMaitlandHunter';
    const NORTHAM_WHEATBELT = 'NorthamWheatbelt';
    const NORTHLAND = 'Northland';
    const OTAGO = 'Otago';
    const PERTH = 'Perth';
    const PORT_HEDLAND_KARRATHA_PILBARA = 'PortHedlandKarrathaPilbara';
    const PORT_MACQUARIE_MID_NORTH_COAST = 'PortMacquarieMidNorthCoast';
    const REST_OF_THE_UK = 'RestoftheUK';
    const RICHMOND_HAWKESBURY = 'RichmondHawkesbury';
    const RIVERLAND_MURRAY_MALLEE = 'RiverlandMurrayMallee';
    const ROCKHAMPTON_CAPRICORN_COAST = 'RockhamptonCapricornCoast';
    const SHEPPARTON_GOULBURN_VALLEY = 'SheppartonGoulburnValley';
    const SOMERSET_LOCKYER = 'SomersetLockyer';
    const SOUTHLAND = 'Southland';
    const SUNSHINE_COAST = 'SunshineCoast';
    const SYDNEY = 'Sydney';
    const TAMWORTH_NORTH_WEST_NSW = 'TamworthNorthWestNSW';
    const TARANAKI = 'Taranaki';
    const TASMAN = 'Tasman';
    const TOOWOOMBA_DARLING_DOWNS = 'ToowoombaDarlingDowns';
    const TOWNSVILLE_NORTHERN_QLD = 'TownsvilleNorthernQLD';
    const TRARALGON_LA_TROBE_VALLEY = 'TraralgonLaTrobeValley';
    const TUMUT_SOUTHERN_HIGHLANDS_SNOWY = 'TumutSouthernHighlandsSnowy';
    const WAGGA_WAGGA_RIVERINA = 'WaggaWaggaRiverina';
    const WAIKATO = 'Waikato';
    const WELLINGTON = 'Wellington';
    const WEST_COAST = 'WestCoast';
    const WHYALLA_EYRE_PENINSULA = 'WhyallaEyrePeninsula';
    const WOLLONGONG_ILLAWARRA_SOUTH_COAST = 'WollongongIllawarraSouthCoast';
    const YARRA_VALLEY_HIGH_COUNTRY = 'YarraValleyHighCountry';
    const YORK_PENINSULA_CLARE_VALLEY = 'YorkPeninsulaClareValley';
}
